2025-05-11 02:33:39,594 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-11 02:33:39,594 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:36:10,567 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-11 02:36:10,567 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:43:13,894 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:43:13,894 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:43:27,067 - ERROR - name 'is_gt' is not defined
Traceback (most recent call last):
  File "/Users/apple/Documents/Bkhan/healthapp/main.py", line 90, in submit_claim
    return jsonify({"message":submit_claim_data_test(url, user, password,secret_key,is_gt,is_ho)})
                                                                                    ^^^^^
NameError: name 'is_gt' is not defined
2025-05-11 02:43:27,069 - INFO - 127.0.0.1 - - [11/May/2025 02:43:27] "[35m[1mPOST /submitClaim HTTP/1.1[0m" 500 -
2025-05-11 02:43:59,874 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:43:59,874 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:45:23,727 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:45:23,728 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:48:28,554 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:48:28,554 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:49:22,479 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:49:22,479 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:49:48,667 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:49:48,667 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:49:56,509 - ERROR - Login failed: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
0   chromedriver                        0x0000000107d828b8 chromedriver + 5986488
1   chromedriver                        0x0000000107d799ea chromedriver + 5949930
2   chromedriver                        0x0000000107832600 chromedriver + 415232
3   chromedriver                        0x0000000107807580 chromedriver + 238976
4   chromedriver                        0x00000001078b2898 chromedriver + 940184
5   chromedriver                        0x00000001078d0f2c chromedriver + 1064748
6   chromedriver                        0x00000001078aa0e3 chromedriver + 905443
7   chromedriver                        0x000000010787661d chromedriver + 693789
8   chromedriver                        0x0000000107877281 chromedriver + 696961
9   chromedriver                        0x0000000107d40580 chromedriver + 5715328
10  chromedriver                        0x0000000107d44445 chromedriver + 5731397
11  chromedriver                        0x0000000107d1aed0 chromedriver + 5562064
12  chromedriver                        0x0000000107d44e7b chromedriver + 5734011
13  chromedriver                        0x0000000107d09de4 chromedriver + 5492196
14  chromedriver                        0x0000000107d67a98 chromedriver + 5876376
15  chromedriver                        0x0000000107d67c60 chromedriver + 5876832
16  chromedriver                        0x0000000107d795b1 chromedriver + 5948849
17  libsystem_pthread.dylib             0x00007ff80acbfdf1 _pthread_start + 99
18  libsystem_pthread.dylib             0x00007ff80acbb857 thread_start + 15
Traceback (most recent call last):
  File "/Users/apple/Documents/Bkhan/healthapp/test.py", line 68, in login_health_app
    email_field = driver.find_element(By.ID, 'user_email')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
0   chromedriver                        0x0000000107d828b8 chromedriver + 5986488
1   chromedriver                        0x0000000107d799ea chromedriver + 5949930
2   chromedriver                        0x0000000107832600 chromedriver + 415232
3   chromedriver                        0x0000000107807580 chromedriver + 238976
4   chromedriver                        0x00000001078b2898 chromedriver + 940184
5   chromedriver                        0x00000001078d0f2c chromedriver + 1064748
6   chromedriver                        0x00000001078aa0e3 chromedriver + 905443
7   chromedriver                        0x000000010787661d chromedriver + 693789
8   chromedriver                        0x0000000107877281 chromedriver + 696961
9   chromedriver                        0x0000000107d40580 chromedriver + 5715328
10  chromedriver                        0x0000000107d44445 chromedriver + 5731397
11  chromedriver                        0x0000000107d1aed0 chromedriver + 5562064
12  chromedriver                        0x0000000107d44e7b chromedriver + 5734011
13  chromedriver                        0x0000000107d09de4 chromedriver + 5492196
14  chromedriver                        0x0000000107d67a98 chromedriver + 5876376
15  chromedriver                        0x0000000107d67c60 chromedriver + 5876832
16  chromedriver                        0x0000000107d795b1 chromedriver + 5948849
17  libsystem_pthread.dylib             0x00007ff80acbfdf1 _pthread_start + 99
18  libsystem_pthread.dylib             0x00007ff80acbb857 thread_start + 15

2025-05-11 02:49:56,632 - ERROR - Login failed: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
0   chromedriver                        0x0000000107d828b8 chromedriver + 5986488
1   chromedriver                        0x0000000107d799ea chromedriver + 5949930
2   chromedriver                        0x0000000107832600 chromedriver + 415232
3   chromedriver                        0x0000000107807580 chromedriver + 238976
4   chromedriver                        0x00000001078b2898 chromedriver + 940184
5   chromedriver                        0x00000001078d0f2c chromedriver + 1064748
6   chromedriver                        0x00000001078aa0e3 chromedriver + 905443
7   chromedriver                        0x000000010787661d chromedriver + 693789
8   chromedriver                        0x0000000107877281 chromedriver + 696961
9   chromedriver                        0x0000000107d40580 chromedriver + 5715328
10  chromedriver                        0x0000000107d44445 chromedriver + 5731397
11  chromedriver                        0x0000000107d1aed0 chromedriver + 5562064
12  chromedriver                        0x0000000107d44e7b chromedriver + 5734011
13  chromedriver                        0x0000000107d09de4 chromedriver + 5492196
14  chromedriver                        0x0000000107d67a98 chromedriver + 5876376
15  chromedriver                        0x0000000107d67c60 chromedriver + 5876832
16  chromedriver                        0x0000000107d795b1 chromedriver + 5948849
17  libsystem_pthread.dylib             0x00007ff80acbfdf1 _pthread_start + 99
18  libsystem_pthread.dylib             0x00007ff80acbb857 thread_start + 15
Traceback (most recent call last):
  File "/Users/apple/Documents/Bkhan/healthapp/test.py", line 68, in login_health_app
    email_field = driver.find_element(By.ID, 'user_email')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
0   chromedriver                        0x0000000107d828b8 chromedriver + 5986488
1   chromedriver                        0x0000000107d799ea chromedriver + 5949930
2   chromedriver                        0x0000000107832600 chromedriver + 415232
3   chromedriver                        0x0000000107807580 chromedriver + 238976
4   chromedriver                        0x00000001078b2898 chromedriver + 940184
5   chromedriver                        0x00000001078d0f2c chromedriver + 1064748
6   chromedriver                        0x00000001078aa0e3 chromedriver + 905443
7   chromedriver                        0x000000010787661d chromedriver + 693789
8   chromedriver                        0x0000000107877281 chromedriver + 696961
9   chromedriver                        0x0000000107d40580 chromedriver + 5715328
10  chromedriver                        0x0000000107d44445 chromedriver + 5731397
11  chromedriver                        0x0000000107d1aed0 chromedriver + 5562064
12  chromedriver                        0x0000000107d44e7b chromedriver + 5734011
13  chromedriver                        0x0000000107d09de4 chromedriver + 5492196
14  chromedriver                        0x0000000107d67a98 chromedriver + 5876376
15  chromedriver                        0x0000000107d67c60 chromedriver + 5876832
16  chromedriver                        0x0000000107d795b1 chromedriver + 5948849
17  libsystem_pthread.dylib             0x00007ff80acbfdf1 _pthread_start + 99
18  libsystem_pthread.dylib             0x00007ff80acbb857 thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Documents/Bkhan/healthapp/test.py", line 111, in submit_claim_data_test
    driver = login_health_app(url,user,password_our,secret_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Documents/Bkhan/healthapp/test.py", line 105, in login_health_app
    raise Exception(f"Login failed: {str(e)}")
Exception: Login failed: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
0   chromedriver                        0x0000000107d828b8 chromedriver + 5986488
1   chromedriver                        0x0000000107d799ea chromedriver + 5949930
2   chromedriver                        0x0000000107832600 chromedriver + 415232
3   chromedriver                        0x0000000107807580 chromedriver + 238976
4   chromedriver                        0x00000001078b2898 chromedriver + 940184
5   chromedriver                        0x00000001078d0f2c chromedriver + 1064748
6   chromedriver                        0x00000001078aa0e3 chromedriver + 905443
7   chromedriver                        0x000000010787661d chromedriver + 693789
8   chromedriver                        0x0000000107877281 chromedriver + 696961
9   chromedriver                        0x0000000107d40580 chromedriver + 5715328
10  chromedriver                        0x0000000107d44445 chromedriver + 5731397
11  chromedriver                        0x0000000107d1aed0 chromedriver + 5562064
12  chromedriver                        0x0000000107d44e7b chromedriver + 5734011
13  chromedriver                        0x0000000107d09de4 chromedriver + 5492196
14  chromedriver                        0x0000000107d67a98 chromedriver + 5876376
15  chromedriver                        0x0000000107d67c60 chromedriver + 5876832
16  chromedriver                        0x0000000107d795b1 chromedriver + 5948849
17  libsystem_pthread.dylib             0x00007ff80acbfdf1 _pthread_start + 99
18  libsystem_pthread.dylib             0x00007ff80acbb857 thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Documents/Bkhan/healthapp/main.py", line 93, in submit_claim
    return jsonify({"message":submit_claim_data_test(url, user, password,secret_key,modifiers,is_submit)})
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Documents/Bkhan/healthapp/test.py", line 113, in submit_claim_data_test
    raise Exception(e)
Exception: Login failed: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=136.0.7103.93)
Stacktrace:
0   chromedriver                        0x0000000107d828b8 chromedriver + 5986488
1   chromedriver                        0x0000000107d799ea chromedriver + 5949930
2   chromedriver                        0x0000000107832600 chromedriver + 415232
3   chromedriver                        0x0000000107807580 chromedriver + 238976
4   chromedriver                        0x00000001078b2898 chromedriver + 940184
5   chromedriver                        0x00000001078d0f2c chromedriver + 1064748
6   chromedriver                        0x00000001078aa0e3 chromedriver + 905443
7   chromedriver                        0x000000010787661d chromedriver + 693789
8   chromedriver                        0x0000000107877281 chromedriver + 696961
9   chromedriver                        0x0000000107d40580 chromedriver + 5715328
10  chromedriver                        0x0000000107d44445 chromedriver + 5731397
11  chromedriver                        0x0000000107d1aed0 chromedriver + 5562064
12  chromedriver                        0x0000000107d44e7b chromedriver + 5734011
13  chromedriver                        0x0000000107d09de4 chromedriver + 5492196
14  chromedriver                        0x0000000107d67a98 chromedriver + 5876376
15  chromedriver                        0x0000000107d67c60 chromedriver + 5876832
16  chromedriver                        0x0000000107d795b1 chromedriver + 5948849
17  libsystem_pthread.dylib             0x00007ff80acbfdf1 _pthread_start + 99
18  libsystem_pthread.dylib             0x00007ff80acbb857 thread_start + 15

2025-05-11 02:49:56,634 - INFO - 127.0.0.1 - - [11/May/2025 02:49:56] "[35m[1mPOST /submitClaim HTTP/1.1[0m" 500 -
2025-05-11 02:52:01,056 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:52:01,056 - INFO - [33mPress CTRL+C to quit[0m
2025-05-11 02:52:03,025 - ERROR - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/Users/apple/Documents/Bkhan/healthapp/main.py", line 88, in submit_claim
    modifiers = (request.form['modifiers'])['data']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
2025-05-11 02:52:03,026 - INFO - 127.0.0.1 - - [11/May/2025 02:52:03] "[35m[1mPOST /submitClaim HTTP/1.1[0m" 500 -
2025-05-11 02:52:17,184 - ERROR - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/Users/apple/Documents/Bkhan/healthapp/main.py", line 88, in submit_claim
    modifiers = (request.form['modifiers'])['data']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
2025-05-11 02:52:17,185 - INFO - 127.0.0.1 - - [11/May/2025 02:52:17] "[35m[1mPOST /submitClaim HTTP/1.1[0m" 500 -
2025-05-11 02:52:41,707 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.18.29:8000
2025-05-11 02:52:41,707 - INFO - [33mPress CTRL+C to quit[0m
